spring:
  datasource:
    url: jdbc:mysql://localhost:3307/eccommerce-proj?useSSL=false&serverTimezone=UTC
    username: root
    password: "@mysqlgamerpro09"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
    security:
      jwt:
        secret: 4iLMlCOA/Det0rynVF6G5zLRkllaDpUIcKqAdqMxHbY=
        expiration-ms: ${JWT_EXP_MS:7200000}
server:
    port: 8080